---
- name:  Collect Artifacts and Reports
  hosts: all
  gather_facts: true

  vars_prompt:
    - name: test_dir
      prompt: "Please enter the path to your tests"
  
  tasks:
   - debug: msg="{{ test_dir }}"

   - synchronize:
       src: "/tmp/tests/"
       dest: "{{ test_dir }}"
       mode: pull
     ignore_errors: true
