---
- name: "Run Scripts on each Inventory Host"
  hosts: master_node
  gather_facts: true
  vars_prompt:
    - name: test_dir
      prompt: "Please enter the path to your tests"

  tasks:
   - name: install rsync and the utilities to copy the tests to the remote host
     become: yes
     package:
       name: "{{ item }}"
       state: latest
     with_items:
       - rsync
       - "{{ ((ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS') and 
              ansible_facts['distribution_major_version'] | int >= 8) | 
                 ternary('python3-libselinux', 'libselinux-python') }}"
       - "{{ ((ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS') and 
              ansible_facts['distribution_major_version'] | int >= 8) | 
                 ternary('python3', 'python2') }}"

   - name: create a directory for the tests on the remote host
     file:
       path: "/tmp/{{ test_dir }}"
       state: directory

   - name: copy the tests onto the hosts where they will be executed
     synchronize:
       src: "{{ test_dir }}/scripts"
       dest: "/tmp/{{ test_dir }}"
       mode: push
     ignore_errors: true

   - name: scan and find the test scripts directory
     find:
       recurse: false
       paths: "/tmp/{{ test_dir }}/scripts"
       file_type: directory
     register: scripts_dir

   - name: loop through script directories and create artifacts directory
     file:
       path: "{{ script_dir }}/artifacts/{{ ansible_architecture }}"
       state: directory
     loop: "{{ scripts_dir.files | map(attribute='path') | list }}"
     loop_control:
        loop_var: script_dir

   - name: loop through script directories and create inventory
     copy:
       src: "{{ inventory }}"
       dest: "{{ script_dir }}/inventory"
     loop: "{{ scripts_dir.files | map(attribute='path') | list }}"
     loop_control:
        loop_var: script_dir

   - name: loop through script directories, run test, and store artifacts
     shell: "bash -x test.sh {{ script_params | default('') }} &> artifacts/{{ ansible_architecture }}/{{ ansible_architecture }}-runlog.txt"
     args:
       chdir: "{{ script_dir }}"
     loop: "{{ scripts_dir.files | map(attribute='path') | list }}"
     loop_control:
        loop_var: script_dir
     ignore_errors: yes
     register: scripts

   - name: fail if the return code is not 0
     fail:
       msg: "The command ({{ item.cmd }}) failed with return code {{ item.rc }}"
     when: item.rc != 0
     with_items: "{{ scripts.results }}"
