---
- name: "Run Scripts on each Inventory Host"
  hosts: all
  gather_facts: true
  roles:
      - role: wtanaka.rsync

  vars_prompt:
    - name: test_dir
      prompt: "Please enter the path to your tests"

  tasks:
   - debug: msg="{{ test_dir }}"

   - file:
       path: "/tmp/{{ test_dir }}"
       state: directory

   - synchronize:
       src: "{{ test_dir }}/scripts"
       dest: "/tmp/{{ test_dir }}"
       mode: push
     ignore_errors: true

   - find:
       recurse: false
       paths: "/tmp/{{ test_dir }}/scripts"
       file_type: directory
     register: scripts

   - shell: "mkdir -p artifacts; bash -x test.sh {{ script_args | default('') }} &> artifacts/{{ ansible_architecture }}-output.txt"
     args:
       chdir: "{{ script_dir }}"
     loop: "{{ scripts.files | map(attribute='path') | list }}"
     loop_control:
        loop_var: script_dir
